INSERT INTO tbl_usuarios (tbl_usuarios_nombre, tbl_usuarios_primer_apellido, tbl_usuarios_segundo_apellido, tbl_usuarios_telefono, tbl_usuarios_direccion, tbl_usuarios_email, tbl_usuarios_pass, tbl_usuarios_tipo, tbl_usuarios_token) VALUES ('Mauricio Alejandro', 'Trejo', 'Miranda', '5511223344', 'patito #1', 'mau@mail.com', 'mau1', 'Administrador', 'OFwXzJIh0owbdaq4Qi5K');
INSERT INTO tbl_usuarios (tbl_usuarios_nombre, tbl_usuarios_primer_apellido, tbl_usuarios_segundo_apellido, tbl_usuarios_telefono, tbl_usuarios_direccion, tbl_usuarios_email, tbl_usuarios_pass, tbl_usuarios_tipo, tbl_usuarios_token) VALUES ('Gabriela', 'Arvizu', 'Velásquez', '5511223344', 'patito #2', 'gaby@mail.com', 'gabigabi', 'Empleado', 'OFwXzJIN0o3bdAq4Qi5K');
INSERT INTO tbl_usuarios (tbl_usuarios_nombre, tbl_usuarios_primer_apellido, tbl_usuarios_segundo_apellido, tbl_usuarios_telefono, tbl_usuarios_direccion, tbl_usuarios_email, tbl_usuarios_pass, tbl_usuarios_tipo, tbl_usuarios_token)VALUES ('Iris', 'Salinas', 'Vergara', '1234123412', 'patito #3', 'irissave@mail.com', '1234', 'Cliente', 'OEwXkJIN0opbd4q4kiaK');

INSERT INTO tbl_materiales (tbl_materiales_material, tbl_materiales_fecha_ingreso, tbl_materiales_fecha_caducidad, tbl_materiales_proveedor, tbl_materiales_descripcion, tbl_materiales_unidad_medida, tbl_materiales_precio, tbl_materiales_cantidad_disponible, tbl_materiales_id)VALUES ('Aluminio', '2024-01-01 06:00:00', '2024-03-31 06:00:00', 'Dentilab', 'Metal para prótesis', 'Piezas', 20, 150, 1);
INSERT INTO tbl_materiales (tbl_materiales_material, tbl_materiales_fecha_ingreso, tbl_materiales_fecha_caducidad, tbl_materiales_proveedor, tbl_materiales_descripcion, tbl_materiales_unidad_medida, tbl_materiales_precio, tbl_materiales_cantidad_disponible, tbl_materiales_id)VALUES ('Yeso', '2024-01-01 06:00:00', '2024-03-31 06:00:00', 'Deposito Dental: La Raza', 'Material de modelado', 'Gramos', 10, 1200, 2);

INSERT INTO tbl_tipo_producto (tbl_tipo_producto_nombre, tbl_tipo_producto_descripción) VALUES ('Protesis Removibles y Prostodoncia', 'descTest');
INSERT INTO tbl_tipo_producto (tbl_tipo_producto_nombre, tbl_tipo_producto_descripción) VALUES ('Restauraciones Metal/Porcelana', 'descTest');
INSERT INTO tbl_tipo_producto (tbl_tipo_producto_nombre, tbl_tipo_producto_descripción) VALUES ('Acrilicos y Resinas', 'descTest');
INSERT INTO tbl_tipo_producto (tbl_tipo_producto_nombre, tbl_tipo_producto_descripción) VALUES ('Restauraciones Metalicas', 'descTest');
INSERT INTO tbl_tipo_producto (tbl_tipo_producto_nombre, tbl_tipo_producto_descripción) VALUES ('Restauraciones Ceramicas Libre de Metal', 'descTest');

INSERT INTO tbl_productos (tbl_productos_nombre,tbl_productos_descripción, tbl_productos_tipo,tbl_productos_precio,tbl_productos_cotizar) VALUES ('Encerado de diagnostico', 'Add Desc here',1,300,0);
INSERT INTO tbl_productos (tbl_productos_nombre,tbl_productos_descripción, tbl_productos_tipo,tbl_productos_precio,tbl_productos_cotizar) VALUES ('Corona Collar Less', 'Add Desc here',2,1500,0);
